### ISSUE TITLE
Release checklist v1.5

### ISSUE THREAD

**Issue by jcheng5** [ramnathv/htmlwidgets#347]
- [x] Create a GitHub issue for release checklist
- [x] Create branch labelled v1.5-rc
- [x] Change the DESCRIPTION and NEWS on this branch to change the version number to the desired version for CRAN
- [x] Commit and push to the RC branch.
- [x] Clean your package directory to remove any extraneous files, including ones that are git-ignored. (Warning, this will delete any unsaved buffers in RStudio! Also, be sure to close RStudio before taking this step!) `git clean -xdf .`
- [x] Build your package. I (jcheng) personally do it from the Mac command line like this:
PATH=$PATH:/Applications/RStudio.app/Contents/MacOS/pandoc R CMD build [pkgdir]
- [x] Do a sanity check by installing/testing the built package.
- [x] Run R CMD check --as-cran pkg_version.tar.gz both locally and on win-builder. You can also use https://r-hub.github.io/rhub/.
- [x] Perform revdepcheck.
- [x] Read every bullet point in the CRAN Policies document if this is the first release of the package. I usually print it out and check off the items one by one.
- [x] Submit to CRAN via their online form.
- [x] If there are R CMD check warnings that are unavoidable, make sure to explain them in the comments.
- [x] When accepted, tag the RC branch with a v1.5 tag, and push the tag to origin.
- [x] Merge RC into master.
- [x] On master, change the package version to 1.5.0.9000.
- [ ] Tweet/blog!
